pipeline {
    agent {
        node {
        label 'maven'
        }
    }

    environment {
    VERSION = readMavenPom().getVersion()
    }

    stages {
        stage ('Get source code') {
            steps {
                git credentialsId: '21d4d238-46ac-4300-a7a7-b5ad76d3b839', url: 'https://github.com/sslbacyhadls/ipr'
            }
        }

        stage ('Build') {
            steps {
                dir ("demoRest"){
                sh 'mvn clean install'
                }
            }
        }

        stage ('Deploy to test'){
            steps {
                dir ("target"){
                sh "scp demoRest-$VERSION.war test_env:/usr/local/tomcat/webapps/"
                }
            }
        }
    }
}
