node ("maven"){
  stages{
    stage ('Get source code') {
        git branch: "${branch}", credentialsId: '21d4d238-46ac-4300-a7a7-b5ad76d3b839', url: 'https://github.com/sslbacyhadls/ipr'
    }

    stage ('Preparation') {
      dir('demoRest') {
        env.APP_VER = sh( script: 'mvn help:evaluate -Dexpression=project.version -q -DforceStdout', returnStdout: true).trim()
        sh "echo ${env.APP_VER}"
      }
    }

    stage ('Maven test'){
      dir('demoRest') {
        sh 'mvn test'
      }
    }

    stage ('Build') {
      dir ("demoRest"){
        sh 'mvn clean install'
      }
    }

    stage ('Archive artifacts'){
      archiveArtifacts artifacts: 'demoRest/target/demoRest-*.war', followSymlinks: false, onlyIfSuccessful: true
    }
   }


  post {
      success {
        mail to: 'shlemov@gmail.com',
            subject: "Pipeline success: ${currentBuild.fullDisplayName}",
            body: "Build completed: app version is ${env.APP_VER}"
      }
      fail {
        mail to: 'shlemov@gmail.com',
            subject: "Pipeline failed: ${currentBuild.fullDisplayName}",
            body: "Error in ${env.BUILD_URL}"
      }
    }
}
