filebeat.inputs:
- type: docker
  combine_partial: false
  containers.ids:
    - '*'
  processors:
    - decode_json_fields:
        fields: ["log"]
        target: ""
        overwrite_keys: true
    - copy_fields:
        fields:
          - from: log
            to: message
        fail_on_error: false
        ignore_missing: true
    - drop_fields:
        fields: ["log"]
        ignore_missing: false


output.logstash:
  hosts: ["logstash:5044"]

output.elasticsearch:
  hosts: ["elasticsearch"]
  username: "elastic"
  password: "e8y1P3a4q-t8-eLy9U-z"

log files:
logging.level: error
logging.to_files: false
logging.to_syslog: false
loggins.metrice.enabled: false
logging.files:
  path: /var/log/filebeat
  name: filebeat
  keepfiles: 7
  permissions: 0644
ssl.verification_mode: none

setup.kibana:
  host: "kibana"
