version: '3.3'
services:
   elasticsearch:
    image: elasticsearch:8.3.3
    container_name: elasticsearch
    ports:
      - "9300:9300"
      - "9200:9200"
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./elasticsearch:/usr/share/elasticsearch/data
    environment:
      CLI_JAVA_OPTS: "-Xms1g -Xmx1g"
      discovery.type: single-node

   logstash:
    image: logstash:8.3.3
    container_name: logstash
    volumes:
      - ./logstash/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./logstash/pipeline:/usr/share/logstash/pipeline
    depends_on:
      - elasticsearch

   kibana:
    image: kibana:8.3.3
    container_name: kibana
    ports:
      - "5601:5601"
    volumes:
      - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
    depends_on:
      - elasticsearch

   filebeat:
    image: docker.elastic.co/beats/filebeat:8.3.3
    container_name: filebeat
    volumes:
      - ./filebeat/filebeat.yml:/usr/share/filebeat/config/filebeat.yml
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro

networks:
 default:
   driver: bridge
   ipam:
     config:
       - subnet: 10.3.0.0/24
