version: '3.8'
services:
   elastic:
    image: elasticsearch:8.3.3
    container_name: elastic
    ports:
      - "9300:9300"
      - "9200:9200"
    container_name: elastic
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro,z
      - ./elasticsearch:/usr/share/elasticsearch/data:z
    environment:
      ELASTIC_PASSWORD: Xu2e0MC4FOJltnKDbjY3
      CLI_JAVA_OPTS: "-Xms1g -Xmx1g"
      discovery.type: single-node

   logstash:
    image: logstash:8.3.3
    container_name: logstash
    volumes:
      - ./logstash/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./logstash/pipeline:/usr/share/logstash/pipeline
    environment:
      LOGSTASH_INTERNAL_PASSWORD: lpass
    depends_on:
      - elasticsearch

   kibana:
    image: kibana:8.3.3
    container_name: kibana
    ports:
      - "5601:5601"
    volumes:
      - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
    environment:
      KIBANA_SYSTEM_PASSWORD: kpass
    depends_on:
      - elasticsearch

   filebeat:
    image: kibana:8.3.3
    container_name: filebeat
    volumes:
      - ./filebeat/filebeat.yml:/usr/share/filebeat/config/filebeat.yml
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
